### PR TITLE
Remove debug `puts` from Outbound::Client#track

### PR DESCRIPTION
**Pull request by c0va23**
Hi!

You missed the debug output into `Outbound::Client#track`.

### CODE REVIEW

**Comment by ciddennis** [comment]
Can we get this merged.

**Comment by smcphill** [comment]
how about `@logger.debug timestamp` ?

**Comment by smcphill** [comment]
btw thanks for the PR @c0va23 👍

**Comment by ciddennis** [comment]
Event debug would be strange as you would just have a bunch of numbers in the log that are not telling you why they existing. Either remove it or put in a longer message that says what it is suppose to be telling you.

**Comment by smcphill** [comment]
I'll ping here when this change makes its way into a new release.

Thanks again 💖

**Pull request merged**
